"""Added projects and issues models

Revision ID: 9c637d80db8d
Revises: 
Create Date: 2024-02-19 00:10:59.536673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c637d80db8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('open', 'in progress', 'done'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.drop_constraint('issues_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('open', 'in progress', 'done'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('open', 'in progress', 'done'),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('issues_ibfk_2', 'users', ['assigned_to'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('open', 'in progress', 'done'),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
